# Generated by Django 2.1.7 on 2019-04-26 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('num', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('publish_time', models.DateField(auto_now_add=True, verbose_name='发表日期')),
                ('modify_time', models.DateField(auto_now=True, verbose_name='最后修改日期')),
                ('data', models.TextField(default='')),
                ('img', models.ImageField(blank=True, null=True, upload_to='article_img/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(default='', max_length=16)),
                ('pwd', models.CharField(default='', max_length=32)),
                ('uid', models.AutoField(db_column='UID', primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='blog_backend.User'),
        ),
        migrations.AddField(
            model_name='paper',
            name='kinds',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='blog_backend.Kind'),
        ),
    ]
