# Generated by Django 2.1.7 on 2019-05-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发表日期'),
        ),
    ]
