# Generated by Django 2.1.7 on 2019-05-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0002_auto_20190505_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='img',
        ),
    ]
