# Generated by Django 2.1.7 on 2019-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='source_data',
            field=models.TextField(default=''),
        ),
    ]
