# Generated by Django 2.1.7 on 2019-05-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_backend', '0005_paper_source_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='paper_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='blog_backend.Paper'),
        ),
    ]
